cards_data = {
    'blue_block_1': {
        'type': 'blue_block',
        'color': 'blue',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'blue_block_2': {
        'type': 'blue_block',
        'color': 'blue',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'green_block_1': {
        'type': 'green_block',
        'color': 'green',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'green_block_2': {
        'type': 'green_block',
        'color': 'green',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'red_block_1': {
        'type': 'red_block',
        'color': 'red',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'red_block_2': {
        'type': 'red_block',
        'color': 'red',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'yellow_block_1': {
        'type': 'yellow_block',
        'color': 'yellow',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'yellow_block_2': {
        'type': 'yellow_block',
        'color': 'yellow',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'color_change_1': {
        'type': 'color_change',
        'color': 'chosen',
        'rank': 'color_change',
        'special': True,
        'variants': ['red_color', 'blue_color', 'green_color', 'yellow_color'],
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['color_change'],
    },
    'color_change_2': {
        'type': 'color_change',
        'color': 'chosen',
        'rank': 'color_change',
        'special': True,
        'variants': ['red_color', 'blue_color', 'green_color', 'yellow_color'],
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['color_change'],
    },
    'color_change_3': {
        'type': 'color_change',
        'color': 'chosen',
        'rank': 'color_change',
        'special': True,
        'variants': ['red_color', 'blue_color', 'green_color', 'yellow_color'],
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['color_change'],
    },
    'color_change_4': {
        'type': 'color_change',
        'color': 'chosen',
        'rank': 'color_change',
        'special': True,
        'variants': ['red_color', 'blue_color', 'green_color', 'yellow_color'],
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['color_change'],
    },
    'red_color': {
        'type': 'red_color',
        'inDeck': False,
        'color': 'red',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'blue_color': {
        'type': 'blue_color',
        'inDeck': False,
        'color': 'blue',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'green_color': {
        'type': 'green_color',
        'inDeck': False,
        'color': 'green',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'yellow_color': {
        'type': 'yellow_color',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'blue_plus_2_1': {
        'type': 'blue_plus',
        'inDeck': True,
        'color': 'blue',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'blue_plus_2_2': {
        'type': 'blue_plus',
        'inDeck': True,
        'color': 'blue',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'green_plus_2_1': {
        'type': 'green_plus',
        'inDeck': True,
        'color': 'green',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'green_plus_2_2': {
        'type': 'green_plus',
        'inDeck': True,
        'color': 'green',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'yellow_plus_2_1': {
        'type': 'yellow_plus',
        'inDeck': True,
        'color': 'yellow',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'yellow_plus_2_2': {
        'type': 'yellow_plus',
        'inDeck': True,
        'color': 'yellow',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'red_plus_2_1': {
        'type': 'red_plus',
        'inDeck': True,
        'color': 'red',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'red_plus_2_2': {
        'type': 'red_plus',
        'inDeck': True,
        'color': 'red',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'plus_4_1': {
        'type': 'plus_4',
        'color': 'chosen',
        'rank': 'plus',
        'special': True,
        'variants': ['blue_plus_4', 'red_plus_4', 'yellow_plus_4', 'green_plus_4'],
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'plus_4_2': {
        'type': 'plus_4',
        'color': 'chosen',
        'rank': 'plus',
        'special': True,
        'variants': ['blue_plus_4', 'red_plus_4', 'yellow_plus_4', 'green_plus_4'],
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'plus_4_3': {
        'type': 'plus_4',
        'color': 'chosen',
        'rank': 'plus',
        'special': True,
        'variants': ['blue_plus_4', 'red_plus_4', 'yellow_plus_4', 'green_plus_4'],
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'plus_4_4': {
        'type': 'plus_4',
        'color': 'chosen',
        'rank': 'plus',
        'special': True,
        'variants': ['blue_plus_4', 'red_plus_4', 'yellow_plus_4', 'green_plus_4'],
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'blue_plus_4': {
        'type': 'blue_plus_4',
        'inDeck': False,
        'color': 'blue',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'red_plus_4': {
        'type': 'red_plus_4',
        'inDeck': False,
        'color': 'red',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'yellow_plus_4': {
        'type': 'yellow_plus_4',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'green_plus_4': {
        'type': 'green_plus_4',
        'inDeck': False,
        'color': 'green',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4'],
    },
    'blue_reverse_1': {
        'type': 'blue_reverse',
        'color': 'blue',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'blue_reverse_2': {
        'type': 'blue_reverse',
        'color': 'blue',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'green_reverse_1': {
        'type': 'green_reverse',
        'color': 'green',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'green_reverse_2': {
        'type': 'green_reverse',
        'color': 'green',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'red_reverse_1': {
        'type': 'red_reverse',
        'color': 'red',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'red_reverse_2': {
        'type': 'red_reverse',
        'color': 'red',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'yellow_reverse_1': {
        'type': 'yellow_reverse',
        'color': 'yellow',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'yellow_reverse_2': {
        'type': 'yellow_reverse',
        'color': 'yellow',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ["blue_reverse", "green_reverse", "yellow_reverse", "red_reverse"],
    },
    'blue_0': {
        'type': 'blue_0',
        'color': 'blue',
        'rank': '0',
        'special': False,
        'comboDown': [],
        'comboUp': ['blue_1'],
        'comboBoth': ['blue_0', 'green_0', 'yellow_0', 'red_0'],
    },
    'blue_1_1': {
        'type': 'blue_1',
        'color': 'blue',
        'rank': '1',
        'special': False,
        'comboDown': ['blue_0'],
        'comboUp': ['blue_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'blue_1_2': {
        'type': 'blue_1',
        'color': 'blue',
        'rank': '1',
        'special': False,
        'comboDown': ['blue_0'],
        'comboUp': ['blue_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'blue_2_1': {
        'type': 'blue_2',
        'color': 'blue',
        'rank': '2',
        'special': False,
        'comboDown': ['blue_1'],
        'comboUp': ['blue_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'blue_2_2': {
        'type': 'blue_2',
        'color': 'blue',
        'rank': '2',
        'special': False,
        'comboDown': ['blue_1'],
        'comboUp': ['blue_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'blue_3_1': {
        'type': 'blue_3',
        'color': 'blue',
        'rank': '3',
        'special': False,
        'comboDown': ['blue_2'],
        'comboUp': ['blue_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'blue_3_2': {
        'type': 'blue_3',
        'color': 'blue',
        'rank': '3',
        'special': False,
        'comboDown': ['blue_2'],
        'comboUp': ['blue_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'blue_4_1': {
        'type': 'blue_4',
        'color': 'blue',
        'rank': '4',
        'special': False,
        'comboDown': ['blue_3'],
        'comboUp': ['blue_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'blue_4_2': {
        'type': 'blue_4',
        'color': 'blue',
        'rank': '4',
        'special': False,
        'comboDown': ['blue_3'],
        'comboUp': ['blue_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'blue_5_1': {
        'type': 'blue_5',
        'color': 'blue',
        'rank': '5',
        'special': False,
        'comboDown': ['blue_4'],
        'comboUp': ['blue_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'blue_5_2': {
        'type': 'blue_5',
        'color': 'blue',
        'rank': '5',
        'special': False,
        'comboDown': ['blue_4'],
        'comboUp': ['blue_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'blue_6_1': {
        'type': 'blue_6',
        'color': 'blue',
        'rank': '6',
        'special': False,
        'comboDown': ['blue_5'],
        'comboUp': ['blue_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'blue_6_2': {
        'type': 'blue_6',
        'color': 'blue',
        'rank': '6',
        'special': False,
        'comboDown': ['blue_5'],
        'comboUp': ['blue_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'blue_7_1': {
        'type': 'blue_7',
        'color': 'blue',
        'rank': '7',
        'special': False,
        'comboDown': ['blue_6'],
        'comboUp': ['blue_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'blue_7_2': {
        'type': 'blue_7',
        'color': 'blue',
        'rank': '7',
        'special': False,
        'comboDown': ['blue_6'],
        'comboUp': ['blue_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'blue_8_1': {
        'type': 'blue_8',
        'color': 'blue',
        'rank': '8',
        'special': False,
        'comboDown': ['blue_7'],
        'comboUp': ['blue_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'blue_8_2': {
        'type': 'blue_8',
        'color': 'blue',
        'rank': '8',
        'special': False,
        'comboDown': ['blue_7'],
        'comboUp': ['blue_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'blue_9_1': {
        'type': 'blue_9',
        'color': 'blue',
        'rank': '9',
        'special': False,
        'comboDown': ['blue_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'blue_9_2': {
        'type': 'blue_9',
        'color': 'blue',
        'rank': '9',
        'special': False,
        'comboDown': ['blue_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'green_0': {
        'type': 'green_0',
        'color': 'green',
        'rank': '0',
        'special': False,
        'comboDown': [],
        'comboUp': ['green_1'],
        'comboBoth': ['blue_0', 'green_0', 'yellow_0', 'red_0'],
    },
    'green_1_1': {
        'type': 'green_1',
        'color': 'green',
        'rank': '1',
        'special': False,
        'comboDown': ["green_0"],
        'comboUp': ['green_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'green_1_2': {
        'type': 'green_1',
        'color': 'green',
        'rank': '1',
        'special': False,
        'comboDown': ["green_0"],
        'comboUp': ['green_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'green_2_1': {
        'type': 'green_2',
        'color': 'green',
        'rank': '2',
        'special': False,
        'comboDown': ['green_1'],
        'comboUp': ['green_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'green_2_2': {
        'type': 'green_2',
        'color': 'green',
        'rank': '2',
        'special': False,
        'comboDown': ['green_1'],
        'comboUp': ['green_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'green_3_1': {
        'type': 'green_3',
        'color': 'green',
        'rank': '3',
        'special': False,
        'comboDown': ['green_2'],
        'comboUp': ['green_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'green_3_2': {
        'type': 'green_3',
        'color': 'green',
        'rank': '3',
        'special': False,
        'comboDown': ['green_2'],
        'comboUp': ['green_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'green_4_1': {
        'type': 'green_4',
        'color': 'green',
        'rank': '4',
        'special': False,
        'comboDown': ['green_3'],
        'comboUp': ['green_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'green_4_2': {
        'type': 'green_4',
        'color': 'green',
        'rank': '4',
        'special': False,
        'comboDown': ['green_3'],
        'comboUp': ['green_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'green_5_1': {
        'type': 'green_5',
        'color': 'green',
        'rank': '5',
        'special': False,
        'comboDown': ['green_4'],
        'comboUp': ['green_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'green_5_2': {
        'type': 'green_5',
        'color': 'green',
        'rank': '5',
        'special': False,
        'comboDown': ['green_4'],
        'comboUp': ['green_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'green_6_1': {
        'type': 'green_6',
        'color': 'green',
        'rank': '6',
        'special': False,
        'comboDown': ['green_5'],
        'comboUp': ['green_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'green_6_2': {
        'type': 'green_6',
        'color': 'green',
        'rank': '6',
        'special': False,
        'comboDown': ['green_5'],
        'comboUp': ['green_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'green_7_1': {
        'type': 'green_7',
        'color': 'green',
        'rank': '7',
        'special': False,
        'comboDown': ['green_6'],
        'comboUp': ['green_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'green_7_2': {
        'type': 'green_7',
        'color': 'green',
        'rank': '7',
        'special': False,
        'comboDown': ['green_6'],
        'comboUp': ['green_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'green_8_1': {
        'type': 'green_8',
        'color': 'green',
        'rank': '8',
        'special': False,
        'comboDown': ['green_7'],
        'comboUp': ['green_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'green_8_2': {
        'type': 'green_8',
        'color': 'green',
        'rank': '8',
        'special': False,
        'comboDown': ['green_7'],
        'comboUp': ['green_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'green_9_1': {
        'type': 'green_9',
        'color': 'green',
        'rank': '9',
        'special': False,
        'comboDown': ['green_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'green_9_2': {
        'type': 'green_9',
        'color': 'green',
        'rank': '9',
        'special': False,
        'comboDown': ['green_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'red_0': {
        'type': 'red_0',
        'color': 'red',
        'rank': '0',
        'special': False,
        'comboDown': [],
        'comboUp': ['red_1'],
        'comboBoth': ['blue_0', 'green_0', 'yellow_0', 'red_0'],
    },
    'red_1_1': {
        'type': 'red_1',
        'color': 'red',
        'rank': '1',
        'special': False,
        'comboDown': ['red_0'],
        'comboUp': ['red_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'red_1_2': {
        'type': 'red_1',
        'color': 'red',
        'rank': '1',
        'special': False,
        'comboDown': ['red_0'],
        'comboUp': ['red_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'red_2_1': {
        'type': 'red_2',
        'color': 'red',
        'rank': '2',
        'special': False,
        'comboDown': ['red_1'],
        'comboUp': ['red_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'red_2_2': {
        'type': 'red_2',
        'color': 'red',
        'rank': '2',
        'special': False,
        'comboDown': ['red_1'],
        'comboUp': ['red_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'red_3_1': {
        'type': 'red_3',
        'color': 'red',
        'rank': '3',
        'special': False,
        'comboDown': ['red_2'],
        'comboUp': ['red_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'red_3_2': {
        'type': 'red_3',
        'color': 'red',
        'rank': '3',
        'special': False,
        'comboDown': ['red_2'],
        'comboUp': ['red_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'red_4_1': {
        'type': 'red_4',
        'color': 'red',
        'rank': '4',
        'special': False,
        'comboDown': ['red_3'],
        'comboUp': ['red_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'red_4_2': {
        'type': 'red_4',
        'color': 'red',
        'rank': '4',
        'special': False,
        'comboDown': ['red_3'],
        'comboUp': ['red_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'red_5_1': {
        'type': 'red_5',
        'color': 'red',
        'rank': '5',
        'special': False,
        'comboDown': ['red_4'],
        'comboUp': ['red_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'red_5_2': {
        'type': 'red_5',
        'color': 'red',
        'rank': '5',
        'special': False,
        'comboDown': ['red_4'],
        'comboUp': ['red_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'red_6_1': {
        'type': 'red_6',
        'color': 'red',
        'rank': '6',
        'special': False,
        'comboDown': ['red_5'],
        'comboUp': ['red_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'red_6_2': {
        'type': 'red_6',
        'color': 'red',
        'rank': '6',
        'special': False,
        'comboDown': ['red_5'],
        'comboUp': ['red_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'red_7_1': {
        'type': 'red_7',
        'color': 'red',
        'rank': '7',
        'special': False,
        'comboDown': ['red_6'],
        'comboUp': ['red_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'red_7_2': {
        'type': 'red_7',
        'color': 'red',
        'rank': '7',
        'special': False,
        'comboDown': ['red_6'],
        'comboUp': ['red_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'red_8_1': {
        'type': 'red_8',
        'color': 'red',
        'rank': '8',
        'special': False,
        'comboDown': ['red_7'],
        'comboUp': ['red_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'red_8_2': {
        'type': 'red_8',
        'color': 'red',
        'rank': '8',
        'special': False,
        'comboDown': ['red_7'],
        'comboUp': ['red_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'red_9_1': {
        'type': 'red_9',
        'color': 'red',
        'rank': '9',
        'special': False,
        'comboDown': ['red_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'red_9_2': {
        'type': 'red_9',
        'color': 'red',
        'rank': '9',
        'special': False,
        'comboDown': ['red_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'yellow_0': {
        'type': 'yellow_0',
        'color': 'yellow',
        'rank': '0',
        'special': False,
        'comboDown': [],
        'comboUp': ['yellow_1'],
        'comboBoth': ['blue_0', 'green_0', 'yellow_0', 'red_0'],
    },
    'yellow_1_1': {
        'type': 'yellow_1',
        'color': 'yellow',
        'rank': '1',
        'special': False,
        'comboDown': ['yellow_0'],
        'comboUp': ['yellow_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'yellow_1_2': {
        'type': 'yellow_1',
        'color': 'yellow',
        'rank': '1',
        'special': False,
        'comboDown': ['yellow_0'],
        'comboUp': ['yellow_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'yellow_2_1': {
        'type': 'yellow_2',
        'color': 'yellow',
        'rank': '2',
        'special': False,
        'comboDown': ['yellow_1'],
        'comboUp': ['yellow_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'yellow_2_2': {
        'type': 'yellow_2',
        'color': 'yellow',
        'rank': '2',
        'special': False,
        'comboDown': ['yellow_1'],
        'comboUp': ['yellow_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'yellow_3_1': {
        'type': 'yellow_3',
        'color': 'yellow',
        'rank': '3',
        'special': False,
        'comboDown': ['yellow_2'],
        'comboUp': ['yellow_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'yellow_3_2': {
        'type': 'yellow_3',
        'color': 'yellow',
        'rank': '3',
        'special': False,
        'comboDown': ['yellow_2'],
        'comboUp': ['yellow_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'yellow_4_1': {
        'type': 'yellow_4',
        'color': 'yellow',
        'rank': '4',
        'special': False,
        'comboDown': ['yellow_3'],
        'comboUp': ['yellow_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'yellow_4_2': {
        'type': 'yellow_4',
        'color': 'yellow',
        'rank': '4',
        'special': False,
        'comboDown': ['yellow_3'],
        'comboUp': ['yellow_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'yellow_5_1': {
        'type': 'yellow_5',
        'color': 'yellow',
        'rank': '5',
        'special': False,
        'comboDown': ['yellow_4'],
        'comboUp': ['yellow_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'yellow_5_2': {
        'type': 'yellow_5',
        'color': 'yellow',
        'rank': '5',
        'special': False,
        'comboDown': ['yellow_4'],
        'comboUp': ['yellow_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'yellow_6_1': {
        'type': 'yellow_6',
        'color': 'yellow',
        'rank': '6',
        'special': False,
        'comboDown': ['yellow_5'],
        'comboUp': ['yellow_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'yellow_6_2': {
        'type': 'yellow_6',
        'color': 'yellow',
        'rank': '6',
        'special': False,
        'comboDown': ['yellow_5'],
        'comboUp': ['yellow_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'yellow_7_1': {
        'type': 'yellow_7',
        'color': 'yellow',
        'rank': '7',
        'special': False,
        'comboDown': ['yellow_6'],
        'comboUp': ['yellow_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'yellow_7_2': {
        'type': 'yellow_7',
        'color': 'yellow',
        'rank': '7',
        'special': False,
        'comboDown': ['yellow_6'],
        'comboUp': ['yellow_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'yellow_8_1': {
        'type': 'yellow_8',
        'color': 'yellow',
        'rank': '8',
        'special': False,
        'comboDown': ['yellow_7'],
        'comboUp': ['yellow_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'yellow_8_2': {
        'type': 'yellow_8',
        'color': 'yellow',
        'rank': '8',
        'special': False,
        'comboDown': ['yellow_7'],
        'comboUp': ['yellow_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'yellow_9_1': {
        'type': 'yellow_9',
        'color': 'yellow',
        'rank': '9',
        'special': False,
        'comboDown': ['yellow_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'yellow_9_2': {
        'type': 'yellow_9',
        'color': 'yellow',
        'rank': '9',
        'special': False,
        'comboDown': ['yellow_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
}
