cards_data = {
    'blue_block': {
        'image': 'blue_block',
        'color': 'blue',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'green_block': {
        'image': 'green_block',
        'color': 'green',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'red_block': {
        'image': 'red_block',
        'color': 'red',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'yellow_block': {
        'image': 'yellow_block',
        'color': 'yellow',
        'rank': 'block',
        'special': True,
        'value': 1,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_block', 'blue_block', 'yellow_block', 'red_block'],
    },
    'color_change_1': {
        'image': 'color_change',
        'color': 'chosen',
        'rank': 'color_change',
        'special': True,
        'variants': ['red_color_1', 'blue_color_1', 'green_color_1', 'yellow_color_1'],
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['color_change_2'],
    },
    'color_change_2': {
        'image': 'color_change',
        'color': 'chosen',
        'rank': 'color_change',
        'special': True,
        'variants': ['red_color_2', 'blue_color_2', 'green_color_2', 'yellow_color_2'],
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['color_change_1'],
    },
    'red_color_1': {
        'image': 'red_color',
        'inDeck': False,
        'color': 'red',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'blue_color_1': {
        'image': 'blue_color',
        'inDeck': False,
        'color': 'blue',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'green_color_1': {
        'image': 'green_color',
        'inDeck': False,
        'color': 'green',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'yellow_color_1': {
        'image': 'yellow_color',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'red_color_2': {
        'image': 'red_color',
        'inDeck': False,
        'color': 'red',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'blue_color_2': {
        'image': 'blue_color',
        'inDeck': False,
        'color': 'blue',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'green_color_2': {
        'image': 'green_color',
        'inDeck': False,
        'color': 'green',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'yellow_color_2': {
        'image': 'yellow_color',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'any',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'blue_plus_2': {
        'image': 'blue_plus',
        'inDeck': False,
        'color': 'blue',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'green_plus_2': {
        'image': 'green_plus',
        'inDeck': False,
        'color': 'green',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'yellow_plus_2': {
        'image': 'yellow_plus',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'red_plus_2': {
        'image': 'red_plus',
        'inDeck': False,
        'color': 'red',
        'rank': 'plus',
        'special': True,
        'value': 2,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'plus_4_1': {
        'image': 'plus_4',
        'color': 'chosen',
        'rank': 'plus',
        'special': True,
        'variants': ['blue_plus_4_1', 'red_plus_4_1', 'yellow_plus_4_1', 'green_plus_4_1'],
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'plus_4_2': {
        'image': 'plus_4',
        'color': 'chosen',
        'rank': 'plus',
        'special': True,
        'variants': ['blue_plus_4_2', 'red_plus_4_2', 'yellow_plus_4_2', 'green_plus_4_2'],
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'blue_plus_4_1': {
        'image': 'blue_plus_4',
        'inDeck': False,
        'color': 'blue',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'red_plus_4_1': {
        'image': 'red_plus_4',
        'inDeck': False,
        'color': 'red',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'yellow_plus_4_1': {
        'image': 'yellow_plus_4',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'green_plus_4_1': {
        'image': 'green_plus_4',
        'inDeck': False,
        'color': 'green',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'blue_plus_4_2': {
        'image': 'blue_plus_4',
        'inDeck': False,
        'color': 'blue',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'red_plus_4_2': {
        'image': 'red_plus_4',
        'inDeck': False,
        'color': 'red',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'yellow_plus_4_2': {
        'image': 'yellow_plus_4',
        'inDeck': False,
        'color': 'yellow',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'green_plus_4_2': {
        'image': 'green_plus_4',
        'inDeck': False,
        'color': 'green',
        'rank': 'plus',
        'special': True,
        'value': 4,
        'active': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
    },
    'blue_reverse': {
        'image': 'blue_reverse',
        'color': 'blue',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'green_reverse': {
        'image': 'green_reverse',
        'color': 'green',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'red_reverse': {
        'image': 'red_reverse',
        'color': 'red',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'yellow_reverse': {
        'image': 'yellow_reverse',
        'color': 'yellow',
        'rank': 'reverse',
        'special': True,
        'comboDown': [],
        'comboUp': [],
        'comboBoth': [],
    },
    'blue_1': {
        'image': 'blue_1',
        'color': 'blue',
        'rank': '1',
        'special': False,
        'comboDown': [],
        'comboUp': ['blue_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'blue_2': {
        'image': 'blue_2',
        'color': 'blue',
        'rank': '2',
        'special': False,
        'comboDown': ['blue_1'],
        'comboUp': ['blue_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'blue_3': {
        'image': 'blue_3',
        'color': 'blue',
        'rank': '3',
        'special': False,
        'comboDown': ['blue_2'],
        'comboUp': ['blue_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'blue_4': {
        'image': 'blue_4',
        'color': 'blue',
        'rank': '4',
        'special': False,
        'comboDown': ['blue_3'],
        'comboUp': ['blue_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'blue_5': {
        'image': 'blue_5',
        'color': 'blue',
        'rank': '5',
        'special': False,
        'comboDown': ['blue_4'],
        'comboUp': ['blue_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'blue_6': {
        'image': 'blue_6',
        'color': 'blue',
        'rank': '6',
        'special': False,
        'comboDown': ['blue_5'],
        'comboUp': ['blue_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'blue_7': {
        'image': 'blue_7',
        'color': 'blue',
        'rank': '7',
        'special': False,
        'comboDown': ['blue_6'],
        'comboUp': ['blue_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'blue_8': {
        'image': 'blue_8',
        'color': 'blue',
        'rank': '8',
        'special': False,
        'comboDown': ['blue_7'],
        'comboUp': ['blue_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'blue_9': {
        'image': 'blue_9',
        'color': 'blue',
        'rank': '9',
        'special': False,
        'comboDown': ['blue_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'green_1': {
        'image': 'green_1',
        'color': 'green',
        'rank': '1',
        'special': False,
        'comboDown': [],
        'comboUp': ['green_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'green_2': {
        'image': 'green_2',
        'color': 'green',
        'rank': '2',
        'special': False,
        'comboDown': ['green_1'],
        'comboUp': ['green_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'green_3': {
        'image': 'green_3',
        'color': 'green',
        'rank': '3',
        'special': False,
        'comboDown': ['green_2'],
        'comboUp': ['green_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'green_4': {
        'image': 'green_4',
        'color': 'green',
        'rank': '4',
        'special': False,
        'comboDown': ['green_3'],
        'comboUp': ['green_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'green_5': {
        'image': 'green_5',
        'color': 'green',
        'rank': '5',
        'special': False,
        'comboDown': ['green_4'],
        'comboUp': ['green_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'green_6': {
        'image': 'green_6',
        'color': 'green',
        'rank': '6',
        'special': False,
        'comboDown': ['green_5'],
        'comboUp': ['green_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'green_7': {
        'image': 'green_7',
        'color': 'green',
        'rank': '7',
        'special': False,
        'comboDown': ['green_6'],
        'comboUp': ['green_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'green_8': {
        'image': 'green_8',
        'color': 'green',
        'rank': '8',
        'special': False,
        'comboDown': ['green_7'],
        'comboUp': ['green_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'green_9': {
        'image': 'green_9',
        'color': 'green',
        'rank': '9',
        'special': False,
        'comboDown': ['green_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'red_1': {
        'image': 'red_1',
        'color': 'red',
        'rank': '1',
        'special': False,
        'comboDown': [],
        'comboUp': ['red_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'red_2': {
        'image': 'red_2',
        'color': 'red',
        'rank': '2',
        'special': False,
        'comboDown': ['red_1'],
        'comboUp': ['red_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'red_3': {
        'image': 'red_3',
        'color': 'red',
        'rank': '3',
        'special': False,
        'comboDown': ['red_2'],
        'comboUp': ['red_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'red_4': {
        'image': 'red_4',
        'color': 'red',
        'rank': '4',
        'special': False,
        'comboDown': ['red_3'],
        'comboUp': ['red_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'red_5': {
        'image': 'red_5',
        'color': 'red',
        'rank': '5',
        'special': False,
        'comboDown': ['red_4'],
        'comboUp': ['red_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'red_6': {
        'image': 'red_6',
        'color': 'red',
        'rank': '6',
        'special': False,
        'comboDown': ['red_5'],
        'comboUp': ['red_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'red_7': {
        'image': 'red_7',
        'color': 'red',
        'rank': '7',
        'special': False,
        'comboDown': ['red_6'],
        'comboUp': ['red_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'red_8': {
        'image': 'red_8',
        'color': 'red',
        'rank': '8',
        'special': False,
        'comboDown': ['red_7'],
        'comboUp': ['red_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'red_9': {
        'image': 'red_9',
        'color': 'red',
        'rank': '9',
        'special': False,
        'comboDown': ['red_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
    'yellow_1': {
        'image': 'yellow_1',
        'color': 'yellow',
        'rank': '1',
        'special': False,
        'comboDown': [],
        'comboUp': ['yellow_2'],
        'comboBoth': ['blue_1', 'green_1', 'yellow_1', 'red_1'],
    },
    'yellow_2': {
        'image': 'yellow_2',
        'color': 'yellow',
        'rank': '2',
        'special': False,
        'comboDown': ['yellow_1'],
        'comboUp': ['yellow_3'],
        'comboBoth': ['blue_2', 'green_2', 'yellow_2', 'red_2'],
    },
    'yellow_3': {
        'image': 'yellow_3',
        'color': 'yellow',
        'rank': '3',
        'special': False,
        'comboDown': ['yellow_2'],
        'comboUp': ['yellow_4'],
        'comboBoth': ['blue_3', 'green_3', 'yellow_3', 'red_3'],
    },
    'yellow_4': {
        'image': 'yellow_4',
        'color': 'yellow',
        'rank': '4',
        'special': False,
        'comboDown': ['yellow_3'],
        'comboUp': ['yellow_5'],
        'comboBoth': ['blue_4', 'green_4', 'yellow_4', 'red_4'],
    },
    'yellow_5': {
        'image': 'yellow_5',
        'color': 'yellow',
        'rank': '5',
        'special': False,
        'comboDown': ['yellow_4'],
        'comboUp': ['yellow_6'],
        'comboBoth': ['blue_5', 'green_5', 'yellow_5', 'red_5'],
    },
    'yellow_6': {
        'image': 'yellow_6',
        'color': 'yellow',
        'rank': '6',
        'special': False,
        'comboDown': ['yellow_5'],
        'comboUp': ['yellow_7'],
        'comboBoth': ['blue_6', 'green_6', 'yellow_6', 'red_6'],
    },
    'yellow_7': {
        'image': 'yellow_7',
        'color': 'yellow',
        'rank': '7',
        'special': False,
        'comboDown': ['yellow_6'],
        'comboUp': ['yellow_8'],
        'comboBoth': ['blue_7', 'green_7', 'yellow_7', 'red_7'],
    },
    'yellow_8': {
        'image': 'yellow_8',
        'color': 'yellow',
        'rank': '8',
        'special': False,
        'comboDown': ['yellow_7'],
        'comboUp': ['yellow_9'],
        'comboBoth': ['blue_8', 'green_8', 'yellow_8', 'red_8'],
    },
    'yellow_9': {
        'image': 'yellow_9',
        'color': 'yellow',
        'rank': '9',
        'special': False,
        'comboDown': ['yellow_8'],
        'comboUp': [],
        'comboBoth': ['blue_9', 'green_9', 'yellow_9', 'red_9'],
    },
}
