type CardData = {
  image: string;
  color: string;
  type: string;
  special?: boolean;
  value?: number;
  active?: boolean;
  comboDown: string[];
  comboUp: string[];
  comboBoth: string[];
};

export const cardsData: { [name: string]: CardData } = {
  blue_block: {
    image: 'blue_block',
    color: 'blue',
    type: 'block',
    special: true,
    value: 1,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_block', 'blue_block', 'yellow_block', 'red_block'],
  },
  green_block: {
    image: 'green_block',
    color: 'green',
    type: 'block',
    special: true,
    value: 1,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_block', 'blue_block', 'yellow_block', 'red_block'],
  },
  red_block: {
    image: 'red_block',
    color: 'red',
    type: 'block',
    special: true,
    value: 1,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_block', 'blue_block', 'yellow_block', 'red_block'],
  },
  yellow_block: {
    image: 'yellow_block',
    color: 'yellow',
    type: 'block',
    special: true,
    value: 1,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_block', 'blue_block', 'yellow_block', 'red_block'],
  },
  color_change_1: {
    image: 'color_change',
    color: 'chosen',
    type: 'color_change',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['color_change_2'],
  },
  color_change_2: {
    image: 'color_change',
    color: 'chosen',
    type: 'color_change',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['color_change_1'],
  },
  red_color_1: {
    image: 'red_color',
    color: 'red',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  blue_color_1: {
    image: 'blue_color',
    color: 'blue',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  green_color_1: {
    image: 'green_color',
    color: 'green',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  yellow_color_1: {
    image: 'yellow_color',
    color: 'yellow',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  red_color_2: {
    image: 'red_color',
    color: 'red',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  blue_color_2: {
    image: 'blue_color',
    color: 'blue',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  green_color_2: {
    image: 'green_color',
    color: 'green',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  yellow_color_2: {
    image: 'yellow_color',
    color: 'yellow',
    type: 'any',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  blue_plus_2: {
    image: 'blue_plus',
    color: 'blue',
    type: 'plus',
    special: true,
    value: 2,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  green_plus_2: {
    image: 'green_plus',
    color: 'green',
    type: 'plus',
    special: true,
    value: 2,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  yellow_plus_2: {
    image: 'yellow_plus',
    color: 'yellow',
    type: 'plus',
    special: true,
    value: 2,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  red_plus_2: {
    image: 'red_plus',
    color: 'red',
    type: 'plus',
    special: true,
    value: 2,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  plus_4_1: {
    image: 'plus_4',
    color: 'chosen',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  plus_4_2: {
    image: 'plus_4',
    color: 'chosen',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  blue_plus_4_1: {
    image: 'blue_plus_4',
    color: 'blue',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  red_plus_4_1: {
    image: 'red_plus_4',
    color: 'red',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  yellow_plus_4_1: {
    image: 'yellow_plus_4',
    color: 'yellow',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  green_plus_4_1: {
    image: 'green_plus_4',
    color: 'green',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  blue_plus_4_2: {
    image: 'blue_plus_4',
    color: 'blue',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  red_plus_4_2: {
    image: 'red_plus_4',
    color: 'red',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  yellow_plus_4_2: {
    image: 'yellow_plus_4',
    color: 'yellow',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  green_plus_4_2: {
    image: 'green_plus_4',
    color: 'green',
    type: 'plus',
    special: true,
    value: 4,
    active: true,
    comboDown: [],
    comboUp: [],
    comboBoth: ['green_plus_2', 'yellow_plus_2', 'blue_plus_2', 'red_plus_2', 'plus_4_1', 'plus_4_2'],
  },
  blue_reverse: {
    image: 'blue_reverse',
    color: 'blue',
    type: 'reverse',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  green_reverse: {
    image: 'green_reverse',
    color: 'green',
    type: 'reverse',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  red_reverse: {
    image: 'red_reverse',
    color: 'red',
    type: 'reverse',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  yellow_reverse: {
    image: 'yellow_reverse',
    color: 'yellow',
    type: 'reverse',
    special: true,
    comboDown: [],
    comboUp: [],
    comboBoth: [],
  },
  blue_1: {
    image: 'blue_1',
    color: 'blue',
    type: '1',
    special: false,
    comboDown: [],
    comboUp: ['blue_2'],
    comboBoth: ['blue_1', 'green_1', 'yellow_1', 'red_1'],
  },
  blue_2: {
    image: 'blue_2',
    color: 'blue',
    type: '2',
    special: false,
    comboDown: ['blue_1'],
    comboUp: ['blue_3'],
    comboBoth: ['blue_2', 'green_2', 'yellow_2', 'red_2'],
  },
  blue_3: {
    image: 'blue_3',
    color: 'blue',
    type: '3',
    special: false,
    comboDown: ['blue_2'],
    comboUp: ['blue_4'],
    comboBoth: ['blue_3', 'green_3', 'yellow_3', 'red_3'],
  },
  blue_4: {
    image: 'blue_4',
    color: 'blue',
    type: '4',
    special: false,
    comboDown: ['blue_3'],
    comboUp: ['blue_5'],
    comboBoth: ['blue_4', 'green_4', 'yellow_4', 'red_4'],
  },
  blue_5: {
    image: 'blue_5',
    color: 'blue',
    type: '5',
    special: false,
    comboDown: ['blue_4'],
    comboUp: ['blue_6'],
    comboBoth: ['blue_5', 'green_5', 'yellow_5', 'red_5'],
  },
  blue_6: {
    image: 'blue_6',
    color: 'blue',
    type: '6',
    special: false,
    comboDown: ['blue_5'],
    comboUp: ['blue_7'],
    comboBoth: ['blue_6', 'green_6', 'yellow_6', 'red_6'],
  },
  blue_7: {
    image: 'blue_7',
    color: 'blue',
    type: '7',
    special: false,
    comboDown: ['blue_6'],
    comboUp: ['blue_8'],
    comboBoth: ['blue_7', 'green_7', 'yellow_7', 'red_7'],
  },
  blue_8: {
    image: 'blue_8',
    color: 'blue',
    type: '8',
    special: false,
    comboDown: ['blue_7'],
    comboUp: ['blue_9'],
    comboBoth: ['blue_8', 'green_8', 'yellow_8', 'red_8'],
  },
  blue_9: {
    image: 'blue_9',
    color: 'blue',
    type: '9',
    special: false,
    comboDown: ['blue_8'],
    comboUp: [],
    comboBoth: ['blue_9', 'green_9', 'yellow_9', 'red_9'],
  },
  green_1: {
    image: 'green_1',
    color: 'green',
    type: '1',
    special: false,
    comboDown: [],
    comboUp: ['green_2'],
    comboBoth: ['blue_1', 'green_1', 'yellow_1', 'red_1'],
  },
  green_2: {
    image: 'green_2',
    color: 'green',
    type: '2',
    special: false,
    comboDown: ['green_1'],
    comboUp: ['green_3'],
    comboBoth: ['blue_2', 'green_2', 'yellow_2', 'red_2'],
  },
  green_3: {
    image: 'green_3',
    color: 'green',
    type: '3',
    special: false,
    comboDown: ['green_2'],
    comboUp: ['green_4'],
    comboBoth: ['blue_3', 'green_3', 'yellow_3', 'red_3'],
  },
  green_4: {
    image: 'green_4',
    color: 'green',
    type: '4',
    special: false,
    comboDown: ['green_3'],
    comboUp: ['green_5'],
    comboBoth: ['blue_4', 'green_4', 'yellow_4', 'red_4'],
  },
  green_5: {
    image: 'green_5',
    color: 'green',
    type: '5',
    special: false,
    comboDown: ['green_4'],
    comboUp: ['green_6'],
    comboBoth: ['blue_5', 'green_5', 'yellow_5', 'red_5'],
  },
  green_6: {
    image: 'green_6',
    color: 'green',
    type: '6',
    special: false,
    comboDown: ['green_5'],
    comboUp: ['green_7'],
    comboBoth: ['blue_6', 'green_6', 'yellow_6', 'red_6'],
  },
  green_7: {
    image: 'green_7',
    color: 'green',
    type: '7',
    special: false,
    comboDown: ['green_6'],
    comboUp: ['green_8'],
    comboBoth: ['blue_7', 'green_7', 'yellow_7', 'red_7'],
  },
  green_8: {
    image: 'green_8',
    color: 'green',
    type: '8',
    special: false,
    comboDown: ['green_7'],
    comboUp: ['green_9'],
    comboBoth: ['blue_8', 'green_8', 'yellow_8', 'red_8'],
  },
  green_9: {
    image: 'green_9',
    color: 'green',
    type: '9',
    special: false,
    comboDown: ['green_8'],
    comboUp: [],
    comboBoth: ['blue_9', 'green_9', 'yellow_9', 'red_9'],
  },
  red_1: {
    image: 'red_1',
    color: 'red',
    type: '1',
    special: false,
    comboDown: [],
    comboUp: ['red_2'],
    comboBoth: ['blue_1', 'green_1', 'yellow_1', 'red_1'],
  },
  red_2: {
    image: 'red_2',
    color: 'red',
    type: '2',
    special: false,
    comboDown: ['red_1'],
    comboUp: ['red_3'],
    comboBoth: ['blue_2', 'green_2', 'yellow_2', 'red_2'],
  },
  red_3: {
    image: 'red_3',
    color: 'red',
    type: '3',
    special: false,
    comboDown: ['red_2'],
    comboUp: ['red_4'],
    comboBoth: ['blue_3', 'green_3', 'yellow_3', 'red_3'],
  },
  red_4: {
    image: 'red_4',
    color: 'red',
    type: '4',
    special: false,
    comboDown: ['red_3'],
    comboUp: ['red_5'],
    comboBoth: ['blue_4', 'green_4', 'yellow_4', 'red_4'],
  },
  red_5: {
    image: 'red_5',
    color: 'red',
    type: '5',
    special: false,
    comboDown: ['red_4'],
    comboUp: ['red_6'],
    comboBoth: ['blue_5', 'green_5', 'yellow_5', 'red_5'],
  },
  red_6: {
    image: 'red_6',
    color: 'red',
    type: '6',
    special: false,
    comboDown: ['red_5'],
    comboUp: ['red_7'],
    comboBoth: ['blue_6', 'green_6', 'yellow_6', 'red_6'],
  },
  red_7: {
    image: 'red_7',
    color: 'red',
    type: '7',
    special: false,
    comboDown: ['red_6'],
    comboUp: ['red_8'],
    comboBoth: ['blue_7', 'green_7', 'yellow_7', 'red_7'],
  },
  red_8: {
    image: 'red_8',
    color: 'red',
    type: '8',
    special: false,
    comboDown: ['red_7'],
    comboUp: ['red_9'],
    comboBoth: ['blue_8', 'green_8', 'yellow_8', 'red_8'],
  },
  red_9: {
    image: 'red_9',
    color: 'red',
    type: '9',
    special: false,
    comboDown: ['red_8'],
    comboUp: [],
    comboBoth: ['blue_9', 'green_9', 'yellow_9', 'red_9'],
  },
  yellow_1: {
    image: 'yellow_1',
    color: 'yellow',
    type: '1',
    special: false,
    comboDown: [],
    comboUp: ['yellow_2'],
    comboBoth: ['blue_1', 'green_1', 'yellow_1', 'red_1'],
  },
  yellow_2: {
    image: 'yellow_2',
    color: 'yellow',
    type: '2',
    special: false,
    comboDown: ['yellow_1'],
    comboUp: ['yellow_3'],
    comboBoth: ['blue_2', 'green_2', 'yellow_2', 'red_2'],
  },
  yellow_3: {
    image: 'yellow_3',
    color: 'yellow',
    type: '3',
    special: false,
    comboDown: ['yellow_2'],
    comboUp: ['yellow_4'],
    comboBoth: ['blue_3', 'green_3', 'yellow_3', 'red_3'],
  },
  yellow_4: {
    image: 'yellow_4',
    color: 'yellow',
    type: '4',
    special: false,
    comboDown: ['yellow_3'],
    comboUp: ['yellow_5'],
    comboBoth: ['blue_4', 'green_4', 'yellow_4', 'red_4'],
  },
  yellow_5: {
    image: 'yellow_5',
    color: 'yellow',
    type: '5',
    special: false,
    comboDown: ['yellow_4'],
    comboUp: ['yellow_6'],
    comboBoth: ['blue_5', 'green_5', 'yellow_5', 'red_5'],
  },
  yellow_6: {
    image: 'yellow_6',
    color: 'yellow',
    type: '6',
    special: false,
    comboDown: ['yellow_5'],
    comboUp: ['yellow_7'],
    comboBoth: ['blue_6', 'green_6', 'yellow_6', 'red_6'],
  },
  yellow_7: {
    image: 'yellow_7',
    color: 'yellow',
    type: '7',
    special: false,
    comboDown: ['yellow_6'],
    comboUp: ['yellow_8'],
    comboBoth: ['blue_7', 'green_7', 'yellow_7', 'red_7'],
  },
  yellow_8: {
    image: 'yellow_8',
    color: 'yellow',
    type: '8',
    special: false,
    comboDown: ['yellow_7'],
    comboUp: ['yellow_9'],
    comboBoth: ['blue_8', 'green_8', 'yellow_8', 'red_8'],
  },
  yellow_9: {
    image: 'yellow_9',
    color: 'yellow',
    type: '9',
    special: false,
    comboDown: ['yellow_8'],
    comboUp: [],
    comboBoth: ['blue_9', 'green_9', 'yellow_9', 'red_9'],
  },
};
